export const data = [
    [
        {
            bg: '#086E4B',
            color: '#FCBE4A',
        "TrainingMax": 69.0000,
        "AuxillaryLift": true,
        "Block": "HypertrophyBlock",
        "AmrapRepTarget": 14,
        "AmrapRepResult": 18,
        "Intensity": 0.6000,
        "Sets": 3,
        "RepsPerSet": 7,
        "RoundingValue": 0.00,
        "Id": 77,
        "Name": "Squat",
        "Category": "Legs",
        "ExerciseDay": 1,
        "ExerciseOrder": 0,
        "Template": "A2SHypertrophy",
        "UserName": "bzzt", "Week": 1,
        "ExerciseMasterId": "CBA60FF0-E5F6-4EB2-9639-4C23543DF8FD",
        "ExerciseCompleted": true,
        "ExerciseTargetCompleted": true
    },
        {
            bg: '#FECBCA',
            color: '#FD5963',
            "TrainingMax": 69.0000,
            "AuxillaryLift": true, "Block": "HypertrophyBlock",
            "AmrapRepTarget": 14, "AmrapRepResult": 0,
            "Intensity": 0.6000, "Sets": 3,
            "RepsPerSet": 7, "RoundingValue": 0.00,
            "Id": 153, "Name": "Squat",
            "Category": "Legs",
            "ExerciseDay": 1,
            "ExerciseOrder": 0,
            "Template": "A2SHypertrophy",
            "UserName": "bzzt",
            "Week": 1,
            "ExerciseMasterId": "564c0328-16f4-4602-9c9f-771d75ba6263",
            "ExerciseCompleted": null,
            "ExerciseTargetCompleted": null
        },
        {
            bg: '#193B8C',
            color: '#FECBCD',
            "StartingReps": 8,
            "StartingSets": 8,
            "RepIncreasePerSet": 2,
            "CurrentReps": 0,
            "CurrentSets": 0,
            "GoalSets": 3,
            "GoalReps": 8,
            "StartingWeight": 0.00,
            "Id": 265,
            "Name": "Low Row",
            "Category": "Back",
            "ExerciseDay": 1,
            "ExerciseOrder": 1,
            "Template": "A2SRepsThenSets",
            "UserName": "bzzt",
            "Week": 1,
            "ExerciseMasterId": "422d37b7-a3bb-4c93-8eef-c775c731267c",
            "ExerciseCompleted": true,
            "ExerciseTargetCompleted": false
        }]

]